name: Release to Hackage

on:
  push:
    branches: main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: freckle/haskell-tag-action@v1

      # If we're reacting to a manually pushed tag, or we just created one
      - if: ${{ startsWith(github.ref, 'refs/tags/') || steps.tag.tag }}
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}
        uses: freckle/stack-upload-action@main
        with:
          pvp-bounds: both
